---
title: "Geocoding Board of Commerce and Industry Approvals"
output: html_notebook
---



```{r setup}

library(tidyverse)
library(readxl)
library(stringr)
library(lubridate)
library(ggmap)
library(taRifx.geo)

# options(BingMapsKey = "ApfMs_rucb7TCYeCRF_lf6aoC5ILi2b29azypiKeZx9O1roEU_gFj4xE-YDtOh1k")

```

```{r raw}

raw <- read_excel("raw_data/approvals.xlsx")

names(raw) <- names(raw) %>% 
  str_trim() %>% 
  str_to_lower() %>% 
  str_replace_all("[^[:alnum:]]+", "_")

raw
glimpse(raw)

```

```{r active}

active <- raw %>% 
  mutate(actual_benefit_amount = str_replace_all(actual_benefit_amount, "\\$", ""),
         actual_benefit_amount = as.numeric(actual_benefit_amount),
         address = str_c(project_location_street_address_line_1,
                         ", ",
                         project_location_city,
                         ", LA"),
         board_approval_date = ymd(board_approval_date)) %>% 
  filter(status_of_award %in% c("Active Contracts", "Completed"),
         board_approval_date >= "2012-01-01", 
         actual_benefit_amount > 0,
         str_length(address) > 2) %>% 
  select(company_name,
         address,
         approval_date = board_approval_date,
         amount = actual_benefit_amount)

active
glimpse(active)

```

```{r bing_geocoder, eval=FALSE}

addresses <- active %>%
  pull(address)

latlon <- addresses %>% map(geocode, service = "bing")

lat <- latlon %>% map_dbl(~.[1])
lon <- latlon %>% map_dbl(~.[2])

with_lonlat <- active %>%
  mutate(lon = lon,
         lat = lat)

```

```{r csv}

with_id <- active %>% 
  mutate(exemption_id = 1:nrow(active)) %>% 
  select(exemption_id, everything())

with_id
glimpse(with_id)

write_csv(with_id, "clean_data/exemptions.csv")

```

```{r ggmap, eval=FALSE}

addresses <- active %>% 
  pull(address)

addresses

xy <- geocode(addresses)

xy

geocodeQueryCheck()

```

```{r lonlat, eval=FALSE}

lonlat <- active %>% 
  bind_cols(xy)

lonlat

```

```{r csv_geocoded, eval=FALSE}

lonlat %>% 
  filter(!is.na(lon),
         !is.na(lat)) %>% 
  write_csv("approvals.csv")

```
